# -*- coding: utf-8 -*-
"""Tabuleiro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o7XHVpRrMaWomSuLs-rwhq5y5yO-tRNJ
"""

from IPython.display import clear_output

import random

tabuleiroPrincipal=[[],[],[],[]]

mylist = ['!','@','#','$','%','*','~','?','!','@','#','$','%','*','~','?']
listVisual=[['@', '*', '?', '#'], ['~', '$', '$', '~'], ['%', '@', '?', '%'], ['!', '#', '*', '!']]
random.shuffle(mylist)

for i in mylist:
  for listAp in tabuleiroPrincipal:
    if len(listAp)<=3:
      listAp.append(i)
      break

def Visualizar():
  
  print("---------TABULEIRO EXEMBPLO--------------")
  
  print("-----------------------------------------")
  for i in listVisual:
    
    print(i)
  print("-----------------------------------------")
def tentativa(list):
  print('|---------------------------------------|')

  print('-----------Tabuleiro Real!---------------')
  
  for j in tabuleiroPrincipal:
    print(j)


  op1=input("Digite a opção 1:")
  p2=input("Digite a opção 2:")
  clear_output()
  tentativa(list)
Visualizar()
tentativa(tabuleiroPrincipal)